# Generated by Django 4.2.7 on 2023-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='english',
            new_name='ادارة_افراد',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hindi',
            new_name='درسات_محاسبيه_باللغه_الانجليزيه',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='maths',
            new_name='شبكات_وامن_معلومات',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='science',
            new_name='محاسبه_اداريه',
        ),
        migrations.AddField(
            model_name='student',
            name='نظمدعم_اتخاذ_القرار',
            field=models.IntegerField(default=0),
        ),
    ]
