# Generated by Django 4.2.7 on 2023-12-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_english_student_ادارة_افراد_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ادارة_افراد',
            new_name='accounting',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='درسات_محاسبيه_باللغه_الانجليزيه',
            new_name='decision_support',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='شبكات_وامن_معلومات',
            new_name='english_accounting',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='محاسبه_اداريه',
            new_name='information_security',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='perecent',
            new_name='percent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='نظمدعم_اتخاذ_القرار',
            new_name='personnel_management',
        ),
    ]
